import { HttpHeaders } from '@angular/common/http';

export interface OptionsApiNewsInterface {
  headers: HttpHeaders;
  params: {
    [param: string]:
      | string
      | number
      | boolean
      | readonly (string | number | boolean)[];
  };
}

// Generated by https://quicktype.io

export interface NewsResponseInterface {
  status: string;
  totalResults: number;
  articles: ArticleInterface[];
}

export interface ArticleInterface {
  source: SourceInterface;
  author?: string;
  title: string;
  description?: string;
  url: string;
  urlToImage?: string;
  publishedAt: string;
  content?: string;
}

export interface SourceInterface {
  id?: string;
  name: string;
}

export interface ArticlesByCategoryInterface {
  [category: string]: {
    page: number;
    articles: ArticleInterface[];
  };
}

export interface MenuSegmentInterface {
  title: string;
  value: string;
}
